FROM node:18

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install -g json-server
COPY db.json .

CMD ["json-server", "--watch", "db.json", "--port", "3000", "--delay", "300", "--host", "0.0.0.0"]